[package]
name = "blog-frontend"
version = "0.0.1"
authors = ["zzy <9809920@qq.com>"]
edition = "2018"

[dependencies]
tide = "0.15.0"
async-std = { version = "1.9.0", features = ["attributes"] }

dotenv = "0.15.0"
lazy_static = "1.4.0"
regex = "1.4.3"

serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"

surf = "2.1.0"
handlebars = "3.5.2"
graphql_client = "0.9.0"

cookie = "0.14.3"
chrono = "0.4.19"
time = "0.2.24"
